Item.search=Sykje
Item.collections=Kolleksjes
Item.content=Ynhâld
Item.add=Tafoegje
Item.remove=Fuortsmite
Item.refresh=Fernije
Item.createSC=Nije notysje oanmeitsje (Alt+N)
Item.titleSC=Titel fan selektearre notysje (Alt+T)
Item.deleteSC=Selektearre notysje wiskje (Alt+D)
Item.selectSearchbarSC=Selektearje sykbalke (Esc)
Item.performSearchSC=Sykopdracht útfiere (Enter)
Item.moveToListSC=Nei list mei notysjes gean (Alt+L)
Item.openCollectionPopupSC=Kolleksjes-popup iepenje (Alt+C)
Item.refreshSC=Alle notysjes fernije (Alt+R)
Item.quitAppSC=De applikaasje ôfslute (Alt+Q)
Item.titleCollectionSC=Titel fan kolleksje (Alt+T)
Item.urlSC=Url fan server (Alt+U)
Item.collectionServerSC=Kolleksje op server (Alt+C)
Item.addCreateCollectionSC=Tafoegje/Oanmeitsje/Bywurkje kolleksje (Alt+A)
Item.listCollectionSC=Gean nei kolleksjelist (Alt+L)
Item.newCollectionSC=Nije kolleksje (Alt+N)
Item.deleteCollectionSC=Kolleksje wiskje (Alt+D)
Item.titleLabel=Titel
Item.serverLabel=Server
Item.collectionLabel=Kolleksje
Item.statusLabel=Status
Item.collectionLocalAndServer=Dizze kolleksje bestiet lokaal en op de server
Item.collectionInServer=Dizze kolleksje bestiet op de server
Item.collectionNotInServer=Dizze kolleksje bestiet net op de server
Item.collectionUpToDate=Dizze kolleksje is aktueel
Item.collectionCreated=Dizze kolleksje is mei súkses oanmakke
Item.collectionAdded=Dizze kolleksje is mei súkses tafoege
Item.collectionUpdated=Dizze kolleksje is bywurke
Item.collectionEmpty=Alle fjilden moatte ynfold wurde
Item.collectionTitleNotUnique=De titel fan in kolleksje moat unyk wêze
Item.collectionServerNotFound=De server waard net fûn
Item.collectionDeletedAndDoesNotExistInServer=Dizze kolleksje is wiskje en bestiet net op de server
Item.collectionError=In ûnferwachte flater is bard
Item.collectionCreate=Oanmeitsje
Item.collectionUpdate=Bywurkje
Item.default=Standert
Item.setAsDefault=Ynstelle as standert
Item.save=OPSLAAN
Item.selectDefault=Selektearje standert
Item.selectAll=Selektearje alles
Item.downloadError=In flater is bard by it downloaden fan in triem
Item.noteDeletionTitle=Wisje befestigje
Item.noteDeletingHeader=Notysje wiskje:
Item.noteDeletingContent=Binne jo wis dat jo dizze notysje wiskje wolle? Dizze aksje kin net weromdraaid wurde.
Item.defaultNotSet=De standert kolleksje is net ynsteld! Om in notysje oan te meitsjen, ynstallearje earst in standert kolleksje.
Item.openFile=Triem iepenje
Item.cantUploadLargerThan=Kin gjin triemmen uploade grutter as 
Item.fileTooBig=Dizze triem is te grut.
Item.fileAddButton=Triem tafoegje
Item.createCollection=Kolleksje oanmeitsje
Item.deleteCollection=Kolleksje wiskje
Item.error=Flater
Item.duplicateTitleError=Titel duplikaasje-flater
Item.serverNotResponding=De server reagearret net
Item.webviewError=In flater is bard by it ferwurkjen fan de webwerjefte
Item.cannotDeleteDefaultCollection=Kin de standert kolleksje net wiskje
Item.unexpectedError=In ûnferwachte flater is bard
Item.responseIsNull=De reaksje is null
Item.imageNotFound=Ofbylding net fûn
Item.errorDeletingFile=Flater by it wiskjen fan triem
Item.noFileSelectedForDeleting=Gjin triem selektearre foar wiskjen.
Item.fileDeleted=Triem wiskje
Item.fileDeletionSucces=De triem is mei súkses wiskje.
Item.failedToDeleteFile=Triem wiskjen mislearre: 
Item.renameFile=Triem opnij beneame
Item.enterANewNameForFile=Fier in nije namme yn foar de triem:
Item.newName=Nije namme:
Item.renamedFileNotFound=Oernamme triem net fûn
Item.renameSuccesful=Opnij beneamen mei súkses
Item.fileRenamedTo=Triem opnij beneamd nei: 
Item.errorRenaming=Flater by opnij beneamen 
Item.File=Triem
Item.defaultCollectionUpdated=Standert kolleksje bywurke
Item.defaultCollectionExplanation=De standert kolleksje sil automatysk selektearre wurde by it oanmeitsjen fan in nije notysje (as de standert ûnder de selektearre kolleksjes is)
Item.collectionWithTitle=Kolleksje mei titel '
Item.hasBeenDeletedLocally=' is lokaal wiskje
Item.collectionStillExistAtUrl=De kolleksje bestiet noch op de server by url '
Item.underCollection= ûnder de kolleksje '
Item.collectionOfCreatedNoteDoesNotExist=De kolleksje fan de notysje dy't jo besykje oan te meitsjen bestiet net!
Item.noteIsIncomplete=Dizze notysje dy't jo besykje te bewurkjen is net folslein!
Item.titleCannotBeEmpty=Titel kin net leech wêze!
Item.titleAlreadyExists=In notysje mei dizze titel bestiet al yn dizze kolleksje.\nKies asjebleaft in oare titel.
Item.noteNotFoundInCollection=De notysje dy't jo besykje te berikken is net fûn yn dizze kolleksje
Item.titleAlreadyExistsInCollection=In notysje mei dizze titel bestiet al yn de kolleksje dy't jo besykje oan dizze notysje ta te heakjen.\nKies asjebleaft in oare kolleksje.
Item.collectionAlreadyDeleted=De kolleksje dy't jo besykje oan dizze notysje ta te heakjen is fan de server wiskje
Item.noteNotInOldCollection=De notysje dy't jo besykje oan in nije kolleksje ta te heakjen waard net fûn yn de âlde kolleksje
Item.noteDeletedButFilesNot=Notysje wiskje, mar triemmen koene net wiskje wurde!
Item.noteNotInThisCollection=De notysje dy't jo besykje te berikken bestiet net yn dizze kolleksje!
Item.collectionAlreadyInServer=De kolleksje dy't jo besykje oan te meitsjen bestiet al op de server
Item.deletedCollectionNotInServer=De kolleksje dy't jo besykje te wiskjen bestiet net op de server
Item.unexpectedServerError=In ûnferwachte serverflater is bard
Item.errorReferencingFile=Flater by it ferwizen nei de triem
Item.fileType=Triem moat fan it type jpg, jpeg, png of gif wêze om ferwiisd te wurden
Item.chooseDifferentFileName=Kies asjebleaft in triem mei in oare namme.
Item.fileNameAlreadyEmbedded=In triem mei dizze namme is al ynfoege.
Item.chooseDestinationFolder=Kies bestimmingmap
Item.downloadSuccesful=Download slagge
Item.successfullyDownloaded=' is mei súkses yn de map delladen: '
Item.fileDoesNotExist=De triem dy't jo iepenje wolle, bestiet net!
Item.fileNotFound=Triem net fûn
Item.fileNameAlreadyExists=Triemnamme bestiet al
Item.unexpectedErrorOccurredWhenCreatingNote=In ûnferwachte flater is bard by it meitsjen fan jo notysje
Item.pickDefaultServer=Standertserver kieze
Item.enterServerURL=Server-URL ynfiere
Item.currentlyNoCollection=Jo hawwe op it stuit gjin kolleksjes.\nFier in server-URL yn om in standertkolleksje oan te meitsjen
Item.fileNotFoundOnServer=Triem net fûn op de server:
Item.serverReturnedstatus= Server joech status werom: 
Item.unexpectedErrorDeletingFile=In ûnferwachte flater barde by it wiskjen fan de triem: 
Item.unexpectedErrorRenamingFile=In ûnferwachte flater barde by it op 'e nij nammen fan de triem: 
Item.errorConnectingToServer=Flater by it ferbinen mei de server
Item.serverAt=De server by '
Item.isUnavailable=' is net beskikber!
Item.collectionWithKey=De kolleksje mei kaai 
Item.doesNotExist= bestiet net
Item.alreadyExists= bestiet al
Item.collectionDoesNotExist=De kolleksje bestiet net
Item.theIndex=De yndeks 
Item.isNotvalid= is net jildich
Item.setOtherDefaultCollection=As jo dizze kolleksje wiskje wolle, stel earst in oare yn as standert
Item.collectionUnavailableServerNotResponding=De kolleksje '%s' is op it stuit net beskikber, om't de server by '%s' net reagearret. Ferwiderje dizze kolleksje of wachtsje oant de server reagearret.
Item.createNewNote=Nije notysje oanmeitsje
Item.titleOfFileCannotBeEmpty=De titel fan de triem mei net leech wêze.
Item.collectionDeleted=Kolleksje wiske
Item.collection=Kolleksje '
Item.removedFromServerAndClient=is fuorthelle fan server en kliïnt.
Item.defaultCollectionCannotBeDeleted=De standertkolleksje kin net wiske wurde. Feroarje de standertkolleksje.
Item.areYouSureDeleteCollection=Binne jo wis dat jo de kolleksje wiskje wolle '
Item.deleteLocallyOrServer=Kies oft jo de kolleksje lokaal of fan 'e server wiskje wolle (net oan te rieden):
Item.deleteLocally=Lokaal wiskje
Item.deleteFromServer=Fan de server wiskje
Item.cancel=Ofbrekke
Item.create=Meitsje (ENTER)
Item.noteTitle=Notysjetitel: 
Item.collectionForNote=Kolleksje (Alt+C)
Item.collectionActionMenu=Aktuele kolleksje bewurkje (Alt+E)
Item.otherShortcutsMenu=Ekstra aksjes (Alt+X)
Item.removeCollectionSC=Kolleksje wiskje (Alt+R)
Item.setDefaultSC=Kolleksje ynstelle as standert (Alt+D)
Item.closeWindowSC=Finster slute (Alt+Q)
Item.noteActionsMenu=Aksjes foar in notysje (Alt+A)
Item.filterMenu=Filterje/Sykje (Alt+F)
Item.editContentSC=Ynhâld fan de selektearre notysje bewurkje (Alt+E)
Item.openCollectionDropdownSC=Kolleksje-dropdown iepenje (Alt+C)
Item.fileContextMenu=Kontekstmenu (Rjochtsklik)
Item.menuItemDownloadFile=Triem delhelje
Item.menuItemDeleteFile=Triem wiskje
Item.menuItemRenameFile=Triem op 'e nij nammen
Item.menuItemInsertReference=Referinsje ynfoegje
Item.labelNoNotes=Hjir binne gjin notysjes
Item.statuscode=Statuskoade: (
Item.EmptyFile=Lege triemnamme
Item.configError=In flater is bard yn it konfiguraasjetriem
Item.quitApplication=Tapassing beëinigje