Item.file=File
Item.quit=Quit
Item.help=
Item.aboutThisApp=
Item.search=Search
Item.collections=Collections
Item.content=Content
Item.add=Add
Item.remove=Remove
Item.refresh=Refresh
Item.createSC=
Item.titleSC=
Item.deleteSC=
Item.selectSearchbarSC=
Item.performSearchSC=
Item.moveToListSC=
Item.openCollectionPopupSC=
Item.refreshSC=
Item.quitAppSC=
Item.titleCollectionSC=
Item.urlSC=
Item.collectionServerSC=
Item.addCreateCollectionSC=
Item.listCollectionSC=
Item.newCollectionSC=
Item.deleteCollectionSC=
Item.buttonSaveCollection=
Item.titleLabel=
Item.serverLabel=
Item.collectionLabel=
Item.statusLabel=