Item.search=Sniff-Sniff (Search)
Item.collections=Catnip Stashes
Item.content=Meow Content
Item.add=Paw Add
Item.remove=Scratch Off
Item.refresh=Stretch (Refresh)
Item.createSC=Scratch new note (Alt+N)
Item.titleSC=Whisker Name (Alt+T)
Item.deleteSC=Trash Note (Alt+D)
Item.selectSearchbarSC=Pounce to Searchbar (Esc)
Item.performSearchSC=Sniff (Enter)
Item.moveToListSC=Jump to Notes (Alt+L)
Item.openCollectionPopupSC=Open Catnip Stash (Alt+C)
Item.refreshSC=Stretch All Notes (Alt+R)
Item.quitAppSC=Exit the Cat Den (Alt+Q)
Item.titleCollectionSC=Whisker Name of Stash (Alt+T)
Item.urlSC=Catnet URL (Alt+U)
Item.collectionServerSC=Stash on Catnet (Alt+C)
Item.addCreateCollectionSC=Add/Create Purr-stash (Alt+A)
Item.listCollectionSC=See All Stashes (Alt+L)
Item.newCollectionSC=New Stash (Alt+N)
Item.deleteCollectionSC=Scratch Stash (Alt+D)
Item.titleLabel=Whisker Name
Item.serverLabel=Catnet
Item.collectionLabel=Catnip Stash
Item.statusLabel=Meow Status
Item.collectionLocalAndServer=This stash is both in the house and on the catnet
Item.collectionInServer=This stash is on the catnet
Item.collectionNotInServer=This stash isn't on the catnet
Item.collectionUpToDate=This stash is paw-some and up-to-date
Item.collectionCreated=New stash created! Purrfect!
Item.collectionAdded=New stash added! Meow!
Item.collectionUpdated=Stash updated! Meow-yeah!
Item.collectionEmpty=All boxes must have catnip!
Item.collectionTitleNotUnique=Each whisker name must be unique!
Item.collectionServerNotFound=Catnet not found. Hiss!
Item.collectionDeletedAndDoesNotExistInServer=This stash is scratched and doesn't exist on catnet
Item.collectionError=Meow-rror happened! Uh-oh!
Item.collectionCreate=Scratch New
Item.collectionUpdate=Update Whiskers
Item.default=Purr-fect Default
Item.setAsDefault=Set as Favorite Spot
Item.save=Save (Meow!)
Item.selectDefault=Pick Favorite
Item.selectAll=Snatch All
Item.downloadError=Oops! Failed to fetch the yarn.
Item.noteDeletionTitle=Are You Sure?
Item.noteDeletingHeader=Scratch This Note:
Item.noteDeletingContent=Meow! This can't be undone. Really scratch it?
Item.defaultNotSet=No favorite spot! Can't make notes without a favorite stash.
Item.openFile=Open Meow File
Item.cantUploadLargerThan=No kitty uploads bigger than 
Item.fileTooBig=This file is too chonky.
Item.fileAddButton=Add Meow File
Item.createCollection=Scratch new stash  
Item.deleteCollection=Scratch stash
Item.error=Hiss! Error!
Item.duplicateTitleError=Duplicate Whisker Name! No way!
Item.serverNotResponding=Catnet is ignoring you. Meow.  
Item.webviewError=Web whisker tangled!
Item.cannotDeleteDefaultCollection=Can't scratch the favorite spot!
Item.unexpectedError=Meow-rror! Unexpected pounce!
Item.responseIsNull=Null? No catnip here!
Item.imageNotFound=No picture of this cat!
Item.errorDeletingFile=Hiss! File won't delete!
Item.noFileSelectedForDeleting=Pick something to scratch first!
Item.fileDeleted=File Scratched
Item.fileDeletionSucces=Scratched it! Purrfect!
Item.failedToDeleteFile=Scratching failed: 
Item.renameFile=Rename Meow File
Item.enterANewNameForFile=Give a new whisker name: 
Item.newName=New Whisker Name: 
Item.renamedFileNotFound=Renamed file not sniffed out
Item.renameSuccesful=Whisker rename success!
Item.fileRenamedTo=Meow file renamed to: 
Item.errorRenaming=Oops! Rename failed.
Item.File=Meow File
Item.defaultCollectionUpdated=Favorite stash updated!
Item.defaultCollectionExplanation=Your favorite stash will auto-fill when scratching new notes (if it's still here!)
Item.collectionWithTitle=Catnip stash with whisker name '
Item.hasBeenDeletedLocally=' got scratched locally
Item.collectionStillExistAtUrl=Still exists on catnet at '
Item.underCollection= under stash '
Item.collectionOfCreatedNoteDoesNotExist=No stash for your new scratchy note!
Item.noteIsIncomplete=Your scratchy note is missing some pawprints!
Item.titleCannotBeEmpty=Whisker name can't be blank!
Item.titleAlreadyExists=A note with this whisker name exists. Pick another!
Item.noteNotFoundInCollection=Can?t find this scratchy note in the stash!
Item.titleAlreadyExistsInCollection=A note with this whisker name is already in that stash. Pick another!
Item.collectionAlreadyDeleted=That stash has been scratched from catnet!
Item.noteNotInOldCollection=This note wasn't found in the old stash. Hiss!
Item.noteDeletedButFilesNot=Note scratched, but files still here!
Item.noteNotInThisCollection=No scratchy note in this stash!
Item.collectionAlreadyInServer=That stash is already on catnet. Purrhaps it's purr-fect?
Item.deletedCollectionNotInServer=This stash isn't on catnet anymore. Bye!
Item.unexpectedServerError=Hiss! Unexpected server meow-rror!
Item.errorReferencingFile=Oops! Can't sniff out the file.
Item.fileType=File must be catnip jpg, jpeg, png, or gif to be sniffed.
Item.chooseDifferentFileName=Pick a file with a new whisker name, meow!
Item.fileNameAlreadyEmbedded=A file with this name is already purr-fectly embedded.
Item.chooseDestinationFolder=Pick a cozy folder spot
Item.downloadSuccesful=Meow-mazing! Download success!
Item.successfullyDownloaded=' was successfully pawed into folder: '
Item.fileDoesNotExist=Hiss! The file you want to paw at doesn?t exist!
Item.fileNotFound=Meow! File not sniffed out!
Item.fileNameAlreadyExists=A file with this whisker name already exists. Purr!
Item.unexpectedErrorOccurredWhenCreatingNote=Oops! A meow-rror happened while scratching your note.
Item.pickDefaultServer=Pick a favorite server
Item.enterServerURL=Enter the Catnet URL
Item.currentlyNoCollection=You don?t have any catnip stashes right now.\nEnter a Catnet URL to create a purr-stash.
Item.fileNotFoundOnServer=Meow! File not found on Catnet:
Item.serverReturnedstatus= Catnet server returned: 
Item.unexpectedErrorDeletingFile=Hiss! An unexpected error scratched the file: 
Item.unexpectedErrorRenamingFile=Oops! Rename scratch failed: 
Item.errorConnectingToServer=Meow! Couldn?t paw into the Catnet.
Item.serverAt=Catnet server at '
Item.isUnavailable=' is not available. Hiss!
Item.collectionWithKey=The stash with the key 
Item.doesNotExist= doesn?t exist. Meow!
Item.alreadyExists= already exists. Purrfect!
Item.collectionDoesNotExist=The stash doesn?t exist. Hiss!
Item.theIndex=The index 
Item.isNotvalid= is not valid. Paw again!
Item.setOtherDefaultCollection=If you want to scratch this stash, pick another favorite first.
Item.collectionUnavailableServerNotResponding=The stash '%s' isn?t available right now because the server at '%s' is silent. Remove the stash or wait for the Catnet to purr.
Item.createNewNote=Scratch new note
Item.titleOfFileCannotBeEmpty=The whisker name of the file can?t be empty!
Item.collectionDeleted=Catnip stash scratched
Item.collection=Stash '
Item.removedFromServerAndClient=was removed from Catnet and your den.
Item.defaultCollectionCannotBeDeleted=You can?t scratch your favorite stash! Pick a new one first.
Item.areYouSureDeleteCollection=Are you sure you want to scratch the stash '
Item.deleteLocallyOrServer=Pick if you want to scratch the stash locally or from Catnet (not recommended):
Item.deleteLocally=Scratch locally
Item.deleteFromServer=Scratch from Catnet
Item.cancel=Paw away
Item.create=Scratch (ENTER)
Item.noteTitle=Note Whisker Name: 
Item.collectionForNote=Catnip Stash (Alt+C)
Item.collectionActionMenu=Edit Current Stash (Alt+E)
Item.otherShortcutsMenu=Extra Paws (Alt+X)
Item.removeCollectionSC=Scratch Stash (Alt+R)
Item.setDefaultSC=Make Stash Favorite (Alt+D)
Item.closeWindowSC=Close Window (Alt+Q)
Item.noteActionsMenu=Note Paws (Alt+A)
Item.filterMenu=Sniff/Find (Alt+F)
Item.editContentSC=Scratch Content of Chosen Note (Alt+E)
Item.openCollectionDropdownSC=Open Stash Dropdown (Alt+C)
Item.fileContextMenu=Paw Context Menu (Right Click)
Item.menuItemDownloadFile=Paw File
Item.menuItemDeleteFile=Scratch File
Item.menuItemRenameFile=Rename File
Item.menuItemInsertReference=Paw in Reference
Item.labelNoNotes=No meow-notes here! Hiss!
Item.statuscode=Hiss-tus code: (
Item.EmptyFile=Empty whisker name!
Item.configError=Meow! A scratch happened in the config file.
Item.quitApplication=Close purr-gram